# Use an official Node.js runtime as a parent image
FROM node:18.17.0-alpine

ARG NEXT_PUBLIC_API_URL

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install any needed packages
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the application
RUN npm run build

# Run the application
CMD ["npm", "start"]

